import React from "react";
import Head from "next/head";
import { Inter } from "@next/font/google";
import { useQuery } from "react-query";
import useDebounce from "@/utils/useDebounce";
import searchPokemons from "@/utils/searchPokemons";
import PokemonsSearchResult from "@/components/PokemonsSearchResult";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [searchValue, setSearchValue] = React.useState("");
  const debounedSearchValue = useDebounce(searchValue, 300);

  const { isLoading, isError, isSuccess, data } = useQuery(
    ["searchPokemons", debounedSearchValue],
    () => searchPokemons(debounedSearchValue),
    {
      enabled: debounedSearchValue.length > 0,
    }
  );

  const renderResult = () => {
    if (isLoading) {
      return <div className="search-message">Loading...</div>;
    }
    if (isError) {
      return <div className="search-message">Something went wrong</div>;
    }
    if (isSuccess) {
      return <PokemonsSearchResult pokemons={data} />;
    }
    return <></>;
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home">
        <h1>Search Your Pokemon</h1>
        <input
          type="text"
          onChange={({ target: { value } }) => setSearchValue(value)}
          value={searchValue}
        />
        {renderResult()}
      </div>
    </>
  );
}
